---
AWSTemplateFormatVersion: 2010-09-09
Description: VPC with private subnets in 3 AZs and gateway endpoints
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: slc
Mappings:
  SubnetConfig:
    Vpc:
      CIDR: 10.0.0.0/16
    Private0:
      CIDR: 10.0.0.0/24
    Private1:
      CIDR: 10.0.16.0/24
    Private2:
      CIDR: 10.0.32.0/24
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock:
        Fn::FindInMap:
          - SubnetConfig
          - Vpc
          - CIDR
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Public
        - Key: Name
          Value: !Sub ${ProjectName}-vpc
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateSubnet0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock:
        Fn::FindInMap:
          - SubnetConfig
          - Private0
          - CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Private
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -subnet-private0-
                - Fn::Select:
                    - 0
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock:
        Fn::FindInMap:
          - SubnetConfig
          - Private1
          - CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Private
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -subnet-private1-
                - Fn::Select:
                    - 1
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock:
        Fn::FindInMap:
          - SubnetConfig
          - Private2
          - CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Network
          Value: Private
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -subnet-private2-
                - Fn::Select:
                    - 2
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateRouteTable0:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -rtb-private0-
                - Fn::Select:
                    - 0
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -rtb-private1-
                - Fn::Select:
                    - 1
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - !Ref ProjectName
                - -rtb-private2-
                - Fn::Select:
                    - 2
                    - Fn::GetAZs: !Ref AWS::Region
        - Key: ProjectName
          Value: !Ref ProjectName
  PrivateSubnetRouteTableAssociation0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet0
      RouteTableId: !Ref PrivateRouteTable0
  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1
  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: '*'
            Effect: Allow
            Principal: '*'
            Action: '*'
      RouteTableIds:
        - !Ref PrivateRouteTable0
        - !Ref PrivateRouteTable1
        - !Ref PrivateRouteTable2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      VpcId: !Ref Vpc
  DynamodbGatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: '*'
            Effect: Allow
            Principal: '*'
            Action: '*'
      RouteTableIds:
        - !Ref PrivateRouteTable0
        - !Ref PrivateRouteTable1
        - !Ref PrivateRouteTable2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcEndpointType: Gateway
      VpcId: !Ref Vpc
Outputs:
  VpcId:
    Description: VpcId of the VPC
    Value: !Ref Vpc
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-Vpc
  DefaultSecurityGroupId:
    Description: SecurityGroupId of the default security group
    Value: !GetAtt Vpc.DefaultSecurityGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-DefaultSecurityGroup
  DefaultNetworkAclId:
    Description: NetworkAclId of the default network ACL
    Value: !GetAtt Vpc.DefaultNetworkAcl
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-DefaultNetworkAcl
  PrivateSubnetId0:
    Description: SubnetId of the private subnet 0
    Value: !Ref PrivateSubnet0
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateSubnet0
  PrivateSubnetId1:
    Description: SubnetId of the private subnet 1
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateSubnet1
  PrivateSubnetId2:
    Description: SubnetId of the private subnet 2
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateSubnet2
  AvailabilityZone0:
    Description: Availability zone 0
    Value: !GetAtt PrivateSubnet0.AvailabilityZone
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AvailabilityZone0
  AvailabilityZone1:
    Description: Availability zone 1
    Value: !GetAtt PrivateSubnet1.AvailabilityZone
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AvailabilityZone1
  AvailabilityZone2:
    Description: Availability zone 2
    Value: !GetAtt PrivateSubnet2.AvailabilityZone
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AvailabilityZone2
  PrivateRouteTableId0:
    Description: RouteTableId of the private route table 0
    Value: !Ref PrivateRouteTable0
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateRouteTable0
  PrivateRouteTableId1:
    Description: RouteTableId of the private route table 1
    Value: !Ref PrivateRouteTable1
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateRouteTable1
  PrivateRouteTableId2:
    Description: RouteTableId of the private route table 2
    Value: !Ref PrivateRouteTable2
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-PrivateRouteTable2
  S3GatewayEndpointId:
    Description: S3 gateway endpoint Id
    Value: !Ref S3GatewayEndpoint
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-S3GatewayEndpoint
  DynamodbGatewayEndpointId:
    Description: DynamoDB gateway endpoint Id
    Value: !Ref DynamodbGatewayEndpoint
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-DynamodbGatewayEndpoint
